#pragma once

//DRAW TEXT
#define REDRAW 1
#define NOREDRAW 0

#define ROWSIZE 0
#define ALLLINE 1

//TYPING MODE
#define INSERT 0
#define OVERWRITE 1

//DRAW BORDER
#define ALLSIDES 1
#define ONLYINFO 0

//CURSOR MOVE 
#define CM_SUCCESS 0
#define CM_ERROR 1
#define CM_MOVE 2
#define CM_NOMOVE 3

//LOADFILE
#define LOADFILEERROR 1
#define LOADFILESUCCESS 2
#define SAVEFILEERROR 3
#define SAVEFILESUCCESS 4

//CHANGES
#define CHANGESSIZE 200

#define CMD_NONE 0
#define CMD_INSERTCHAR 1
#define CMD_DELETEAFTERCHAR 2
#define CMD_UNDO 3
#define CMD_REDO 4
#define CMD_INSERTCHARAFTER 5
#define CMD_DELETEBEFORECHAR 6
#define CMD_OVERWRITECHAR 7

//MODES
#define MODE_EDIT 0
#define MODE_COMMANDS 1

#define COMMANDMODE_MENUHEIGHT 4
#define COMMANDMODE_COMMANDMAXSIZE 20
#define COMMANDMODE_FEEDBACKSIZE 3
#define COMMANDMODE_FEEDBACKMAXSIZE 50

#define COMMANDMODE_ALLOWEDSYMBOLSSIZE 69
const char COMMANDMODE_ALLOWEDSYMBOLS[COMMANDMODE_ALLOWEDSYMBOLSSIZE] = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm 1234567890-+./\\:";

#define COMMANDMODE_COMMANDSIZE 14

#define COMMANDMODE_ERROR 0
#define COMMANDMODE_SUCCESS 1
#define COMMANDMODE_SINTAX 2

//filepath
#define FILEPATHMAXSIZE 70

//update visible
#define CLS 1
#define TXT 2